### ISSUE TITLE
design it for windows pc

### ISSUE THREAD

**Issue by luxit** [mehulj94/Cyberoam-Account-Crack#1]
I have python 2.7 and python 3.5 installed in my pc but when i run it gives an error that "sleep" command is not recognised. it looks like the script is designed only for linux. please make required modification in script so that it can be used in windows pc. thanks 
mail-: luxitjoshi@gmail.com

**Comment by mehulj94** [comment]
The issue has been fixed. Make sure you have all the imported libraries installed. I have made significant changes in the code. Let me know if you face further problems.

**Comment by luxit** [comment]
the code is working like charm.......... thanks🤗🤗🤗
